### ISSUE TITLE
Add canonical url in the template 

### ISSUE THREAD

**Issue by cderv** [apreshill/quillt#11]
Instead of in **pkgdown** itself: https://github.com/r-lib/pkgdown/issues/1527

This should be possible using the new `in-header.html` (related to #5)

**Comment by cderv** [comment]
Would that be a new parameter to set in 
````yaml
template:
  package: quillt
  params:
    canonical: https://pkgs.rstudio.com/blastula
```

Or would that just use the `url:` provided already (e.g **blogdown**: https://github.com/rstudio/blogdown/blob/f324246c8a5ae72b9cd7c6d5b2eac3b65187652a/_pkgdown.yml#L3) ? 

This field is used by pkgdown already, and it seems it will be set to pkgs.rstudio.com urls even in GH website, will it ? 
https://pkgdown.r-lib.org/reference/build_site.html#yaml-config

We just need to decide what to add in the header template: 

* Which link(s) ? 
* Only on homepage ? or for all the pages ?
